### ISSUE TITLE
GPU configuration

### ISSUE THREAD

**Issue by xwhjy** [RoySheffer/im2wav#3]
Hi Roy,

Thanks for your interesting work! I was wondering how many GPUs are required at least to perform the training (bs=2)?

**Comment by RoySheffer** [comment]
You can perform the training with a single GPU as well.

**Comment by xwhjy** [comment]
> You can perform the training with a single GPU as well.

And how long does it take to train?

**Comment by RoySheffer** [comment]
depends on your GPU size but ~1mil iterations with bs=16
