### ISSUE TITLE
Can sample length be changed for a pretrained model?

### ISSUE THREAD

**Issue by Darius-H** [RoySheffer/im2wav#4]
https://github.com/RoySheffer/im2wav/blob/aff5a8022a01760052f633ec525e36d1cdf70403/models/sample.py#L215

I found the sample length argument in models/sample.py, but change it does not change the generated audio length.
Is there any way to change the generated audio length for a pretrained model?
It seems that sample_length depends on self.sample_length = self.n_ctx*self.raw_to_tokens and cannot be changed.

**Comment by RoySheffer** [comment]
https://github.com/RoySheffer/im2wav/blob/aff5a8022a01760052f633ec525e36d1cdf70403/models/sample.py#L216

can this be what you are looking for?

**Comment by Darius-H** [comment]
So if i want to change the audio duration to 10 seconds. how should i change the code? thanks.



---Original---
From: ***@***.***&gt;
Date: Wed, Mar 15, 2023 23:31 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [RoySheffer/im2wav] Can sample length be changed for a pretrainedmodel? (Issue #4)




 
https://github.com/RoySheffer/im2wav/blob/aff5a8022a01760052f633ec525e36d1cdf70403/models/sample.py#L216
 
can this be what you are looking for?

**Comment by Darius-H** [comment]
If i want to change the audio duration to 10 seconds. how should i change the code? It seems that hop_fraction argument also need to be properly set. Thanks.

> https://github.com/RoySheffer/im2wav/blob/aff5a8022a01760052f633ec525e36d1cdf70403/models/sample.py#L216
> 
> can this be what you are looking for?

**Comment by RoySheffer** [comment]
you can try something like adding

-sliding_window_total_sample_length 163840 -hop_fraction 0.5 0.5

**Comment by xwhjy** [comment]
> you can try something like adding
> 
> -sliding_window_total_sample_length 163840 -hop_fraction 0.5 0.5

Hi Roy! I'm new to audio processing. Please forgive me if I'm asking a really dumb question. I'm wondering why here the total sample length is set as 163840. If the audio duration is 10 seconds and the sampling rate is 16kHz, wouldn't the length be 160000 (10*16000)? Thanks for your time!

**Comment by RoySheffer** [comment]
Hey we operate the sampling in a discrete space in lower resolution quoting from the paper (https://arxiv.org/pdf/2211.03089.pdf):

**"The first codebook is applied after three convolutional layers, resulting in a downsampling factor of 8. Then,
the second codebook is applied after two additional convolutional layers, resulting in an overall downsampling factor of
32. This corresponds to 2000 tokens per second in the UP
model and 500 tokens per second in the LOW model."**

I recommend reading the paper of more information.

**Comment by RoySheffer** [comment]
Hey we operate the sampling in a discrete space in a lower resolution. Quoting from the paper (https://arxiv.org/pdf/2211.03089.pdf):

**"The first codebook is applied after three convolutional layers, resulting in a downsampling factor of 8. Then,
the second codebook is applied after two additional convolutional layers, resulting in an overall downsampling factor of
32. This corresponds to 2000 tokens per second in the UP
model and 500 tokens per second in the LOW model."**

For us to be able to generate some length it is required to meet some conditions e.g to divide in some number with no residual.
We can theoretically do all the calculations for you and generate the closest feasible length that is larger than the length you asked for and clip it in the end.
To be honest this is simply a mechanism that wasn't used at all in the paper and I just played with it regardless so I didn't make it "product ready".
You are welcome to open a PR with the change :)

**Comment by xwhjy** [comment]
> you can try something like adding
> 
> -sliding_window_total_sample_length 163840 -hop_fraction 0.5 0.5

Hi Roy! I'm able to use this to generate 10s audio with video condition sampling successfully. But for image condition sampling, I got this error
```
  File "/home/im2wav/models/prior/conditioners.py", line 197, in forward
    total_length, offset, length, clip = y[:, 0, 0:1], y[:, 0, 1:2], y[:, 0, 2:3], y[:, :, 3:]
```
I checked the shape of y, upon the error happening, it had the shape of [2, 0, 515].
The full printing info before error is:
```
{'experiment_name': 'image_CLIP', 'save_dir': 'samples', 'model_name': 'my_model', 'vq_cp': None, 'prior_cp': None, 'up_cp': None, 'resultsDir': '', 'bs': 2, 'first': None, 'cfg_s': 3.0, 'wav_per_object': 2, 'p_grid': [0], 'k_grid': [0], 'CLIP_dir': None, 'CLIP_dict': 'image_CLIP/CLIP.pickle', 'testing_file': None, 'models': ['im2wav'], 'hop_fraction': [0.5, 0.5], 'sample_length': 65536, 'sliding_window_total_sample_length': 163840}
Using cuda True
2 ['bongo1', 'dog1']
num batches is 2
0:00:00.117190 using cuda hps:{'experiment_name': 'image_CLIP_use_samplev2_10s', 'save_dir': 'samples', 'model_name': 'im2wav', 'vq_cp': '../pre_trained/vqvae.tar', 'prior_cp': '../pre_trained/low.tar', 'up_cp': '../pre_trained/up.tar', 'resultsDir': 'k_top0_p_top0', 'bs': 2, 'first': None, 'cfg_s': 3.0, 'wav_per_object': 2, 'p_grid': [0], 'k_grid': [0], 'CLIP_dir': None, 'CLIP_dict': 'image_CLIP/CLIP.pickle', 'testing_file': None, 'models': ['im2wav'], 'hop_fraction': [0.5, 0.5], 'sample_length': 65536, 'sliding_window_total_sample_length': 163840, 'total_sample_length': 163840, 'num_batches': 2, 'top_k': 0, 'top_p': 0}
Restored from ../pre_trained/vqvae.tar
Restored from ../pre_trained/vqvae.tar
0: Loading vqvae in eval mode
Restored from ../pre_trained/low.tar
Level:1, Cond downsample:None, Raw to tokens:32, Sample length:65536
0: Converting to fp16 params
Restored from ../pre_trained/low.tar
0: Loading prior in eval mode
Restored from ../pre_trained/up.tar
Conditioning on 1 above level(s)
Checkpointing convs
Checkpointing convs
Level:0, Cond downsample:4, Raw to tokens:8, Sample length:65536
0: Converting to fp16 params
Restored from ../pre_trained/up.tar
0: Loading prior in eval mode
0:00:07.240264 im2wav starting from 0 top_k: 0 top_p: 0   --------------------------------------------------------------------
required 2 in [0, 2]
i: 0 num_batches: 2 progress: 0.0 0:00:07.240821 before multi_level_sample_window
0:00:07.436486 Sampling 2048 tokens for [0,2048]. Conditioning on 0 tokens z.shape=torch.Size([2, 0])
0:00:07.436914 0.0 30
0:00:07.436948 using frames [0, 122] out of the total 1 frames 122.0 =? 0.4
Ancestral sampling 2 samples with temp=1.0, top_k=0, top_p=0
self.video_clip True y shape torch.Size([2, 1, 515])
self.video_clip True y shape torch.Size([2, 1, 515])
2048/2048 [03:02<00:00, 11.22it/s] 
0:03:11.425018 Sampling 2048 tokens for [1024,3072]. Conditioning on 1024 tokens z.shape=torch.Size([2, 1024])
0:03:11.425334 2.048 30
0:03:11.425361 using frames [61, 183] out of the total 1 frames 122.0 =? 0.4
Primed sampling 2 samples with temp=1.0, top_k=0, top_p=0
self.video_clip True y shape torch.Size([2, 0, 515])
```

Do you have any clues on how to fix this? Thanks!
