### ISSUE TITLE
"skvideo.io.vread" reports error

### ISSUE THREAD

**Issue by xwhjy** [RoySheffer/im2wav#6]
Hi Roy,

Thank you for your prompt reply! I really appreciate that you always respond quickly.

I'm collecting CLIP representation of VGGSound videos by running the ``collect_video_CLIP.py`` following your instruction. However, for video ``l6q7shFb8zs_000041`` and ``EktPRpYX9KI_000038``, it reports this error:
```
Traceback (most recent call last):
  File "/home/anaconda3/envs/myenv/lib/python3.8/site-packages/skvideo/io/ffmpeg.py", line 271, in _read_frame_data
    assert len(arr) == framesize
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "debug.py", line 194, in <module>
    check_corrupted_video()
  File "debug.py", line 173, in check_corrupted_video
    videodata = skvideo.io.vread(video)
  File "/home/anaconda3/envs/myenv/lib/python3.8/site-packages/skvideo/io/io.py", line 148, in vread
    for idx, frame in enumerate(reader.nextFrame()):
  File "/home/anaconda3/envs/myenv/lib/python3.8/site-packages/skvideo/io/ffmpeg.py", line 297, in nextFrame
    yield self._readFrame()
  File "/home/anaconda3/envs/myenv/lib/python3.8/site-packages/skvideo/io/ffmpeg.py", line 281, in _readFrame
    s = self._read_frame_data()
  File "/home/anaconda3/envs/myenv/lib/python3.8/site-packages/skvideo/io/ffmpeg.py", line 275, in _read_frame_data
    raise RuntimeError("%s" % (err1,))
RuntimeError
```

I was wondering if this happens to you as well? I obtain 199,176 videos from the VGGSound dataset and only these two cannot be processed.

**Comment by RoySheffer** [comment]
Sure np and sorry but I didn't

**Comment by mayqinxu** [comment]
> Hi Roy, > > Thanks for your quick reply! I really appreciate that you always reply quickly. > > I collect CLIP representations of VGGSound videos by running `collect_video_CLIP.py` according to your instructions. However, for the videos `l6q7shFb8zs_000041` and `EktPRpYX9KI_000038` it reports this error: > > `` > Traceback (most recent call last): > File "/home/anaconda3/envs/myenv/lib/python3.8/site-packages/skvideo/io/ffmpeg.py", line 271, in _read_frame_data > assert len(arr) == framesize > AssertionError > > While handling the above exception, another exception occurred: > > Traceback (most recent call last): > File "debug.py", line 194, in <module> > check_corrupted_video() > File "debug.py", line 173, in check_corrupted_video > videodata = skvideo.io.vread(video) > file "/home/anaconda3/envs/myenv/lib/python3.8/site-packages/skvideo/io/io.py", line 148, in vread > for idx, frame in enumerate(reader.nextFrame()): > file "/home/anaconda3/envs/myenv/lib/python3.8/site-packages/skvideo/io/ffmpeg.py", line 297, in nextFrame > yield self._readFrame() > file "/home/anaconda3/envs/myenv/lib/python3.8/site-packages/skvideo/io/ffmpeg.py", line 281, in _readFrame > s = self._read_frame_data() > File "/home/anaconda3/envs/myenv/lib/python3.8/site-packages/skvideo/io/ffmpeg.py", line 275, in _read_frame_data > raise RuntimeError("%s" % (err1,)) > RuntimeError > ``` > I was wondering if this happens to you too? I get 199,176 videos from the VGGSound dataset and only these two cannot be processed.

Hi xwhjy, I am wondering how long it takes you to preprocess all the videos in VGGSound? It seems to take a very long time.

**Comment by xwhjy** [comment]
@mayqinxu Hi! I cannot remember the time but it did take quite a long time to process all the videos in VGGSound.
