### ISSUE TITLE
Evaluation code

### ISSUE THREAD

**Issue by xwhjy** [RoySheffer/im2wav#7]
Hi Roy! Are you planning to release the code of how to compute those metrics reported in your paper (FAD, KL, CS, ACC)? Thanks!

**Comment by RoySheffer** [comment]
For sure. It is on my TODO list just need to find the time as I did it using preprocessed saved data and not on the fly but should be pretty simple.

**Comment by xwhjy** [comment]
> For sure. It is on my TODO list just need to find the time as I did it using preprocessed saved data and not on the fly but should be pretty simple.

Looking forward to it!
