### ISSUE TITLE
Video Data Preprocessing

### ISSUE THREAD

**Issue by mayqinxu** [RoySheffer/im2wav#8]
Hi Roy,

I am collecting the CLIP representation of VGGSound videos by running the collect_video_CLIP.py file. I had to change some codes for some reason, and now it takes a long time to calculate all the videos.  I'm wondering how long will it take to collect all the CLIP features for videos in the VGGSound dataset through the original collect_video_CLIP.py ?

BTW, I just changed the way loading clip model for my server is offline.

**Comment by RoySheffer** [comment]
I did it once and didn't time it but It depends on how many GPUs you use to distribute the calculation and what are their memory size.
