### ISSUE TITLE
Unable to get ACC result reported in the paper

### ISSUE THREAD

**Issue by xwhjy** [RoySheffer/im2wav#9]
Hi Roy!
For the pretrained im2wav model, I can reproduce most of the metrics reported in your paper. However, when I use pretrained PaSST to compute the accuracy over 30 ImageHear classes for 15,446 VGGSound test set, I only get 23.6% for the reference audio and 13.4% for the generated audio by the pretrained im2wav model you provide. I've only got 2800 samples from VGGSound-test that belong to ImageHear class following the mapping provided [here](https://github.com/RoySheffer/im2wav/blob/main/Data/meta.py).

The pretrained PaSST is specified as `get_model_passt(arch="passt_s_swa_p16_128_ap476",  n_classes=527, s_patchout_t=40, s_patchout_f=4)` following [their repo](https://github.com/kkoutini/PaSST).

Is it possible for you to share your code of computing ACC? Thanks!

**Comment by RoySheffer** [comment]
Hey!
It is on my TODO list I need to find the time to adjust the evaluation code.
23.6% for the reference audio is very low, I think you might have a bug. 
Make sure you are using the right SR (32khz if I remember correctly)
